version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - GUID=1000
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
volumes:
    mongodata: