version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      - PUID=1000
      - GUID=1000
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
  # app:
  #   container_name: app
  #   build: .
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - 'mongo'
  #   links:
  #     - mongo
  #   environment:
  #     - DATABASE_CONNECTION_STRING=mongodb://mongo:27017/my_database
volumes:
  mongodata:
  redis:
    driver: local
